### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by daliwali** [fortunejs/fortune#264]
Meta-issue to keep track of smaller things to do.

- [ ] String literals in types #260 
- [ ] Transactions per request #262
- [ ] Multiple instances in browser #263
- [ ] Improve comment messages
- [ ] Add custom Promise again, ES6 Promise too slow

**Comment by jmeas** [comment]
@daliwali let me know if you'd like help with any of this. I'm still learning my way around the code, but I'd be happy to learn and help out more with this project.
